### ISSUE TITLE
documentation: add type annotations

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/zahner_potentiostat#1]
Please add type annotations.

#### Background
I just called `zahner_potentiostat.scpi_control.searcher.SCPIDeviceSearcher.searchZahnerDevices` and its documentation says:

> :returns: Returns a list with serial numbers of connected Zahner devices. The serial numbers are strings.

But its function signature is:

```python
def searchZahnerDevices(self) -> Any:
```
According to its docstring, this method does not return `Any` but some `list[str]` (I guess?)

**Comment by maxkrapp1** [comment]
The documentation has to be adapted to the latest Python version with the type hints and so on. This will also be done in the next release.

Thanks for your feedback.

**Comment by ilka-schulz** [comment]
Thanks! I just started adding type annotations every time I edit some piece of it. (specifically #8) But it is probably a good idea to do this all at once in a structured manner.

**Comment by maxkrapp1** [comment]
This will be done with the next release.
