### ISSUE TITLE
typing: add meaningful return types to methods in SCPIDevice

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/zahner_potentiostat#14]
The class `SCPIDevice` has many methods which return some `str` which appears to be some status response from the device. In order to properly encapsulate complexity, they should return some result type (e.g. `Optional[int]` for success with int response or failure).

also see PR #13

**Comment by maxkrapp1** [comment]
The statuses to revise answers are also on the todo list in the future. Normally, the string "ok" is always returned.

With setRaiseOnErrorEnabled an exception is thrown as soon as an error from this [list](https://doc.zahner.de/zahner_potentiostat/scpi_control/error.html) occurs. This is always enabled by default and you can just ignore the response and work with try and catch.

**Comment by maxkrapp1** [comment]
The exception system was revised with your @ilka-schulz help.

However, the string is still returned for maximum flexibility.
