### ISSUE TITLE
feature request: progress indicator

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/zahner_potentiostat#17]
It would be really nice if I could get a progress information (potentially estimated) from the device. I implemented my own progress indicator for constant current / constant voltage measurements with fixed duration. My colleague really appreciates the progress indicator in the GUI, so I would like to add the same feature to all other measurement techniques.

- Is there already an SCPI command to get progress information?
- Is it possible to make some clever estimations on the required time?

**Comment by maxkrapp1** [comment]
Predicting the measurement duration is a very complex issue and is not available as an SCPI command.

The maximum time is always the time you pass to the primitives:

* Potentiostatic or galvanostatic polarization  
  * [measurePolarization()](https://doc.zahner.de/zahner_potentiostat/scpi_control/control.html#zahner_potentiostat.scpi_control.control.SCPIDevice.measurePolarization)  
* Open circuit voltage/potential scan  
  * [measureOCV()](https://doc.zahner.de/zahner_potentiostat/scpi_control/control.html#zahner_potentiostat.scpi_control.control.SCPIDevice.measureOCV)  
  * [measureOCVScan()](https://doc.zahner.de/zahner_potentiostat/scpi_control/control.html#zahner_potentiostat.scpi_control.control.SCPIDevice.measureOCVScan)  
* Ramps potentiostatic or galvanostatic  
  * [measureRampValueInTime()](https://doc.zahner.de/zahner_potentiostat/scpi_control/control.html#zahner_potentiostat.scpi_control.control.SCPIDevice.measureRampValueInTime)  
  * [measureRampValueInScanRate()](https://doc.zahner.de/zahner_potentiostat/scpi_control/control.html#zahner_potentiostat.scpi_control.control.SCPIDevice.measureRampValueInScanRate)  
  * [measureRampScanRateForTime()](https://doc.zahner.de/zahner_potentiostat/scpi_control/control.html#zahner_potentiostat.scpi_control.control.SCPIDevice.measureRampScanRateForTime)  
* Staircase potentiostatic or galvanostatic  
  * [measureIEStairs()](https://doc.zahner.de/zahner_potentiostat/scpi_control/control.html#zahner_potentiostat.scpi_control.control.SCPIDevice.measureIEStairs)  

A termination before the maximum time is possible if termination criteria like voltage or current limits are reached.

The simplest way is probably, if the GUI, which also parameterizes the measurement with times, implements a progress indicator based on the maximum time.
