### ISSUE TITLE
feature request: galvano electroimpedance spectography

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/zahner_potentiostat#18]
Searching through the `SCPIDevice` class, I could not find a `measure*()` method to do a "galvano electroimpedance spectography". Is it hidden somewhere or is this measurement technique not yet implemented? It is basically a must-have for me and I just assumed the library would support it...

**Comment by maxkrapp1** [comment]
A galvanostatic impedance spectrum can be measured. This is possible if a Zennium is connected to the power potentiostats via EPC.

![grafik](https://user-images.githubusercontent.com/56908566/211739250-cc6dbb13-5af1-4274-b34a-de9ff4df9a6a.png)

The package `zahner_potentiostat` supports all new devices like PP2x2, EL1002 and XPOT2. These devices can be controlled via USB with DC methods without a Zennium.

If you have a Zennium connected to the device via EPC, then you must use the `thales_remote` package. This package is used to control the Zennium, which can then control the PP2x2, EL1002 and XPOT2 devices via EPC. With the Zennium and EPC it is also possible to measure potentiostatic and galvanostatic EIS and CV.

In the readmes of our three Python repositories we explain the exact usage of the packages.

- [zahner_potentiostat](https://github.com/Zahner-elektrik/zahner_potentiostat)
- [thales_remote](https://github.com/Zahner-elektrik/Thales-Remote-Python)
- [zahner_analysis](https://github.com/Zahner-elektrik/Zahner-Analysis-Python)


If you contact me by mail (maximilian.krapp@zahner.de) I can send you further information material from my workshop at the Kronacher Impedance Days.

**Comment by maxkrapp1** [comment]
As written, this is implemented with the [thales_remote](https://github.com/Zahner-elektrik/Thales-Remote-Python) library.

**Comment by ilka-schulz** [comment]
@maxkrapp1 Could you please add a line to the README referring to the `thales_remote` package for EIS measurements?

**Comment by maxkrapp1** [comment]
Done 👍
