### ISSUE TITLE
cleanup: use pyproject.toml instead of setup.py

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/zahner_potentiostat#2]
`setup.py` is deprecated and should be replaced with `pyproject.toml`.

**Comment by maxkrapp1** [comment]
Thanks for the tip I will check this.

**Comment by maxkrapp1** [comment]
With the next release I will change it to toml when I have successfully used toml for the thales_remote package.

**Comment by maxkrapp1** [comment]
I have just changed it to pyproject.toml
