### ISSUE TITLE
which formatter to use

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/zahner_potentiostat#4]
I am starting to create PRs. Which formatter shall I use? I usually use `black`.

**Comment by maxkrapp1** [comment]
In the past I have used Eclipse with PyDev and have used the built-in PyDev formatter.
But I have changed to the black formatter and VSCode for the next update, which is coming soon. Some of the examples are not yet formatted with black.

So the black formatter matches.

**Comment by ilka-schulz** [comment]
awesome, thanks!
