### ISSUE TITLE
implement non-blocking measure methods

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/zahner_potentiostat#8]
I am following the [basic example](https://github.com/Zahner-elektrik/Zahner-Remote-Python/blob/main/Examples/BasicIntroduction/BasicIntroduction.py#L27) to take some simple measurements:

```python
ZahnerPP2x2.setSamplingFrequency(25)
ZahnerPP2x2.setCoupling(COUPLING.POTENTIOSTATIC)

ZahnerPP2x2.setMaximumTimeParameter(15)

for voltage in [0, 3, 0]:
    ZahnerPP2x2.setVoltageParameter(voltage)
    ZahnerPP2x2.measurePolarization()
```

It appears the calls to `zahner_potentiostat.scpi_control.control.SCPIDevice.measurePolarization` are executed in a blocking manner. This is most unfortunate because in many applications, one wants their calling code to do a lot of other things in the mean time, e.g. I/O, GUI, management.

I am going to hack sth. together by replacing `_writeCommandToInterfaceAndReadLine`, `sendStringAndWaitForReplyString`, etc. I guess you can expect my PR soon...

**Comment by maxkrapp1** [comment]
The idea is that the library is used for blocking measurements in one thread. GUI IO and other tasks should take place in a separate thread.

When you program a GUI you should always use a "worker" thread, which performs the task.

**Comment by ilka-schulz** [comment]
I implemented the non-blocking behavior within 20 min on my laptop for my first attempts at using Zahner devices. It was really just  two function signatures to change...

> When you program a GUI you should always use a "worker" thread, which performs the task.

I am seriously considering doing that. I already use a thread pool to do device discovery but I am reluctant to write my entire engine multi-threaded. I am mostly a Rust programmer, so I am extremely afraid of using multi-threading in unsafe languages like Python, so I am trying a single-threaded state machine with calls non-blocking functions first. Getting data races during production would be catastrophic – maybe I can later rewrite my application in Rust :crab:

**Comment by maxkrapp1** [comment]
You are welcome to contact me then we can possibly discuss the topic in a zoom meeting.
maximilian.krapp@zahner.de

**Comment by ilka-schulz** [comment]
fyi: multithreading with Python is indeed hard:

Main Thread:
```python
# `device` is some initialized SCPIDevice, created on main thread
# configure device
device.setSamplingFrequency(frequency=25)
device.setCoupling(control.COUPLING.GALVANOSTATIC)
device.setCurrentParameter(1.0)
device.setMaximumTimeParameter(5)
# start worker thread afterwards
process = multiprocessing.Process(
    target=run, args=(device,)
)
process.start()
```

Worker thread:

```python
def run(device: control.SCPIDevice):
    device.measurePolarization()
```

The potentiostat runs as expected but some exception occurs in `device.measurePolarization` at the very end of the specified 5 s:

```text
  File "/home/user/.local/lib/python3.9/site-packages/zahner_potentiostat/scpi_control/serial_interface.py", line 336, in _telegramListenerJob
    raise ValueError("Nothing sent, which includes the answer: " + line)
ValueError: Nothing sent, which includes the answer: ok
```

I will look through the documentation but I would say that this is unexpected behavior. (would not have happened in Rust :wink:)

**Comment by maxkrapp1** [comment]
Yes, with the Python GIL it is indeed a bit special. I also prefer to program C++.

Your problem has never occurred with me. I have always worked with threads instead of processes.

This [example](https://github.com/Zahner-elektrik/Zahner-Remote-Python/blob/main/Examples/ImpedanceMultiCellCycle/ImpedanceMultiCellCycle.ipynb) is an implementation of mine.

I will have a look at it soon what fails with processes. Because the behavior is really unexpected. It is so that as soon as a request is sent over one of the two channels it is registered in the list. And in your example the response "ok" is received but in neither of the queues (queue.SimpleQueue()) a request was made. Something fails here.

**Comment by ilka-schulz** [comment]
Thank you very much for being such an active maintainer! I could not imagine getting better support when diving into a new library for controlling some measurement equipment!

**Comment by ilka-schulz** [comment]
> I also prefer to program C++.

fyi: I used to be an absolute C++ fan girl until a year ago. If you like C++, you will probably love Rust. That is what many C++ developer experience when they try Rust for a while.

**Comment by ilka-schulz** [comment]
> This [example](https://github.com/Zahner-elektrik/Zahner-Remote-Python/blob/main/Examples/ImpedanceMultiCellCycle/ImpedanceMultiCellCycle.ipynb) is an implementation of mine.

Using `threading` instead of `multiprocessing` works like a charm. It is quite a plug-in replacement and my code now works as expected.

**Comment by maxkrapp1** [comment]
I'm glad to hear that.
But I will have another look at it anyway because multiprocessing should work as well.

**Comment by maxkrapp1** [comment]
I have tested multiprocessing.

The problem is if you pass the device object as args, it must be serialized and brought into the other process. This is not possible because of the internally used objects that can not be serialized. If you use threading you don't have this problem because everything in Python runs in the same process with the GIL.

```python
from zahner_potentiostat.scpi_control.searcher import SCPIDeviceSearcher
from zahner_potentiostat.scpi_control.serial_interface import (
    SerialCommandInterface,
    SerialDataInterface,
)
from zahner_potentiostat.scpi_control.control import *
from zahner_potentiostat.scpi_control.datahandler import DataManager
from zahner_potentiostat.scpi_control.datareceiver import TrackTypes
from zahner_potentiostat.display.onlinedisplay import OnlineDisplay

from jupyter_utils import executionInNotebook
import multiprocessing
import threading


def run(device: SCPIDevice):

    ZahnerPP2x2.setVoltageParameter(0)
    ZahnerPP2x2.measurePolarization()

    ZahnerPP2x2.setVoltageParameter(3)
    ZahnerPP2x2.measurePolarization()

    ZahnerPP2x2.setVoltageParameter(0)
    ZahnerPP2x2.measurePolarization()


if __name__ == "__main__":
    deviceSearcher = SCPIDeviceSearcher()
    deviceSearcher.searchZahnerDevices()
    commandSerial, dataSerial = deviceSearcher.selectDevice()

    ZahnerPP2x2 = SCPIDevice(
        SerialCommandInterface(commandSerial), SerialDataInterface(dataSerial)
    )

    ZahnerPP2x2.setSamplingFrequency(25)
    ZahnerPP2x2.setCoupling(COUPLING.POTENTIOSTATIC)

    ZahnerPP2x2.setMaximumTimeParameter(5)

    """
    Doesnt Work
    """
    process = multiprocessing.Process(target=run, args=(ZahnerPP2x2,))
    process.start()
    process.join()

    """
    Works
    """
    # process = threading.Thread(target=run, args=(ZahnerPP2x2,))
    # process.start()
    # process.join()

    dataReceiver = ZahnerPP2x2.getDataReceiver()

    completeData = dataReceiver.getCompletePoints()

    timeData = completeData[TrackTypes.TIME.toString()]
    voltageData = completeData[TrackTypes.VOLTAGE.toString()]
    currentData = completeData[TrackTypes.CURRENT.toString()]

    print(currentData[0:10])

    dataManager = DataManager(dataReceiver)
    dataManager.plotTIUData("polarization.pdf", 10, 5)

    dataManager.saveDataAsText("polarization.txt")

    ZahnerPP2x2.close()
    print("finish")
```

If you want to work with multiprocessing, the object must be created in the process.

```python
from zahner_potentiostat.scpi_control.searcher import SCPIDeviceSearcher
from zahner_potentiostat.scpi_control.serial_interface import (
    SerialCommandInterface,
    SerialDataInterface,
)
from zahner_potentiostat.scpi_control.control import *
from zahner_potentiostat.scpi_control.datahandler import DataManager
from zahner_potentiostat.scpi_control.datareceiver import TrackTypes
from zahner_potentiostat.display.onlinedisplay import OnlineDisplay

from jupyter_utils import executionInNotebook
import multiprocessing
import threading


def run():
    deviceSearcher = SCPIDeviceSearcher()
    deviceSearcher.searchZahnerDevices()
    commandSerial, dataSerial = deviceSearcher.selectDevice()

    ZahnerPP2x2 = SCPIDevice(
        SerialCommandInterface(commandSerial), SerialDataInterface(dataSerial)
    )

    ZahnerPP2x2.setSamplingFrequency(25)
    ZahnerPP2x2.setCoupling(COUPLING.POTENTIOSTATIC)

    ZahnerPP2x2.setMaximumTimeParameter(5)

    ZahnerPP2x2.setVoltageParameter(0)
    ZahnerPP2x2.measurePolarization()

    ZahnerPP2x2.setVoltageParameter(3)
    ZahnerPP2x2.measurePolarization()

    ZahnerPP2x2.setVoltageParameter(0)
    ZahnerPP2x2.measurePolarization()
    dataReceiver = ZahnerPP2x2.getDataReceiver()

    completeData = dataReceiver.getCompletePoints()

    timeData = completeData[TrackTypes.TIME.toString()]
    voltageData = completeData[TrackTypes.VOLTAGE.toString()]
    currentData = completeData[TrackTypes.CURRENT.toString()]

    print(currentData[0:10])

    dataManager = DataManager(dataReceiver)
    dataManager.plotTIUData("polarization.pdf", 10, 5)

    dataManager.saveDataAsText("polarization.txt")

    ZahnerPP2x2.close()
    print("finish")


if __name__ == "__main__":

    process = multiprocessing.Process(target=run)
    process.start()
    process.join()

```

**Comment by ilka-schulz** [comment]
@maxkrapp1 Thanks for the research! Maybe mention this somewhere in the docs. I am personally fine with using `threading` but this sounds like sth. that should be documented somehow.

**Comment by maxkrapp1** [comment]
Yes I have documented it now and in the new release it is described in the ImpedanceMultiCellCycle.ipynb example and included in the object description.
