### ISSUE TITLE
bug: parameter in method docstring but not used

### ISSUE THREAD

**Issue by ilka-schulz** [Zahner-elektrik/zahner_potentiostat#9]
`zahner_potentiostat.scpi_control.serial_interface.SerialCommandInterface.sendString` has a parameter declared in its documentation which is never used.

**Comment by maxkrapp1** [comment]
Will be fixed in the next release.

**Comment by maxkrapp1** [comment]
Fixed with commit 6d210947ca02cc7607018df6982153eb1c86258f in version 1.1.0.
